CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True
DATASET:
  AUGMENT: True
  BASIC_TRANSFORM: True
  BBOX_CROP_FLAG: False
  DATA_FORMAT: jpg
  INCLUDE_CLASSES: ['ra', 'normal']
  JSON: data/json/tmp0418/joint/final_samples_both_only_v2.json
  MEAN: [0.1147, 0.1147, 0.1147]
  PKL: data/pkl/output200x300.pkl
  ROOT: 
  STD: [0.2194, 0.2194, 0.2194]
  TARGET_CLASSES: ['ra', 'normal']
  TEST_SET: valid
  TRAIN_SET: train
  USE_PATCH: True
  USE_RAW: True
  USE_PKL: False
  REPORT: False
  MULTI_RUN: True
  MULTI_RUN_SEEDING: True
DATA_DIR: 
DEBUG:
  DEBUG: False
  GRAPH_DEBUG: True
DEVICE: GPU
GPUS: 0
KFOLD:
  KFOLD_SIZE: 5
  P: 0
  TEST_SET_RATIO: 0.10
  USE_KFOLD: True
LOG_DIR: 
MODEL:
  INIT_WEIGHTS: True
  NAME: feature_extractor3
  PRETRAINED: True
  EXTRA:
    WITH_ATTN: False
    ONLYCAT: True
    VIEWCAT: False
    RAW: resnet
    PATCH: None
  FREEZE:
    BACKBONE: False
    PROJECTION: False
    CLASSIFIER: False
OUTPUT_DIR: ./output/twobranchmodel
PHASE: train
PRINT_FREQ: 10
TEST:
  BATCH_SIZE_PER_GPU: 64
  TEST_SET_RATIO: 0.10
TRAIN:
  BATCH_SIZE_PER_GPU: 64
  BEGIN_EPOCH: 0
  CHECKPOINT: 
  DECAY: 0.0005
  END_EPOCH: 50
  GAMMA1: 0.99
  GAMMA2: 0.0
  LR: 0.001
  LR_FACTOR: 0.1
  LR_STEP: [90, 110]
  MODE: min
  MOMENTUM: 0.9
  NESTEROV: False
  OPTIMIZER: adam
  PATIENCE: 5
  RESUME: False
  SCHEDULER: ReduceLROnPlateau
  SHUFFLE: True
  WD: 0.0001
  factor: 0.5
WORKERS: 4
