GPUS: '0'
DATA_DIR: ''
OUTPUT_DIR: 'output/'
LOG_DIR: 'log/'
WORKERS: 1
PRINT_FREQ: 50
DATASET:
  DATASET: 'coco'
  ROOT: 'data/coco/'
  DATA_FORMAT: 'jpg'
  TEST_SET: 'JPEGImages' # Need to annotation for caunuri 
  TRAIN_SET: 'JPEGImages' # Need to annotation for caunuri
  FLIP_PAIR: [[1, 12],[2,13],[3,14],[4,10],[5,11],[6,9],[15,17]]
  FLIP: True
  ROT_FACTOR: 0
  SCALE_FACTOR: 0
MODEL:
  NAME: 'pose_resnet'
  PRETRAINED: 'ckpt/detector/final_state.pth.tar'
# MayBe need to use pretrained weight for foot x-ray image.
#  PRETRAINED: 'output/retrained/coco/pose_resnet_50/384x288_d256x3_adam_lr1e-3-RHPE-Foot-N2-Doctor-noflip/final_state.pth.tar'
  IMAGE_SIZE:
  - 288
  - 384
  NUM_JOINTS: 17
  EXTRA:
    TARGET_TYPE: 'gaussian'
    HEATMAP_SIZE:
    - 72
    - 96
    SIGMA: 2
    FINAL_CONV_KERNEL: 1
    DECONV_WITH_BIAS: false
    NUM_DECONV_LAYERS: 3
    NUM_DECONV_FILTERS:
    - 256
    - 256
    - 256
    NUM_DECONV_KERNELS:
    - 4
    - 4
    - 4
    NUM_LAYERS: 50
LOSS:
  USE_TARGET_WEIGHT: true
TRAIN:
  COCO_FILE: 'data/coco/annotations/Foot/new/foot_new_0210__train.json' # Also, Need new annotation file.
  BATCH_SIZE: 4
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 100
  RESUME: false
  OPTIMIZER: 'adam'
  LR: 0.001
  LR_FACTOR: 0.1
  LR_STEP:
  - 90
  - 120 
  WD: 0.0001
  GAMMA1: 0.99
  GAMMA2: 0.0
  MOMENTUM: 0.9
  NESTEROV: false
TEST:
  BATCH_SIZE: 512
  COCO_FILE: 'data/json/foot_new_0210__test.json'
  # COCO_BBOX_FILE: 'data/json/joint/ocr_results_v1.1.json' # 25.04.18 이전 버전
  COCO_BBOX_FILE: 'data/json/tmp0418/joint/bbox_for_debugging_jd.json'
  BBOX_THRE: 1.0
  FLIP_TEST: false
  IMAGE_THRE: 0.8
  IN_VIS_THRE: 0.2
  MODEL_FILE: 'ckpt/detector/model_best.pth.tar' # Need new one.
  OKS_THRE: 0.3
  USE_GT_BBOX: false
DEBUG:
  DEBUG: false
  SAVE_BATCH_IMAGES_GT: false
  SAVE_BATCH_IMAGES_PRED: false
  SAVE_HEATMAPS_GT: false
  SAVE_HEATMAPS_PRED: false
