CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True
DATASET:
  AUGMENT: True
  BALANCE: True
  BASIC_TRANSFORM: True
  BBOX_CROP_FLAG: False
  DATA_FORMAT: jpg
  INCLUDE_CLASSES: ['oa', 'ra', 'gout', 'normal']
  JSON: data.json
  MEAN: [0.1147, 0.1147, 0.1147]
  PKL: data/pkl/output_report(eng).pkl
  REPORT: True
  ROOT: 
  STD: [0.2194, 0.2194, 0.2194]
  TARGET_CLASSES: ['oa', 'ra', 'gout', 'normal']
  TEST_SET: valid
  TRAIN_SET: train
  USE_PATCH: True
  USE_RAW: True
DATA_DIR: 
DEBUG:
  DEBUG: False
  GRAPH_DEBUG: True
DECODER:
  EXTRA:
    LEARNING_RATE: 5e-05
    MAX_SEQ_LENGTH: 128
    MODEL_SIZE: small
    OPTIMIZER: AdamW
    TEST_BATCH_SIZE: 8
    TRAIN_BATCH_SIZE: 8
    VAL_BATCH_SIZE: 8
    PT: None
  INIT_WEIGHTS: True
  NAME: meerkat-7b-v1.0
  PRETRAINED: True
  USE_LORA: True
DEVICE: GPU
GPUS: 0
KFOLD:
  KFOLD_SIZE: 5
  P: 0
  TEST_SET_RATIO: 0.15
  USE_KFOLD: True
LOG_DIR: 
MODEL:
  EXTRA:
    CKPT: wandb/run-multiclass-classifier/files/best_model.pth
    PATCH: Resnet
    RAW: swin-t
    USE_CKPT: True
    FREEZE: True
  INIT_WEIGHTS: True
  NAME: feature_extractor
  PRETRAINED: True
OUTPUT_DIR: 
PHASE: train
PRINT_FREQ: 10
TEST:
  BATCH_SIZE_PER_GPU: 8
  TEST_SET_RATIO: 0.15
TRAIN:
  USE_GRAD_CLIP: True
  GRADIENT_ACCUMULATION_STEPS: 2
  BATCH_SIZE_PER_GPU: 8
  BEGIN_EPOCH: 0
  CHECKPOINT: 
  DECAY: 0.0005
  END_EPOCH: 100
  GAMMA1: 0.99
  GAMMA2: 0.0
  LOSS: BCELoss
  LR: 2e-4
  LR_FACTOR: 0.1
  LR_STEP: [90, 110]
  MODE: min
  MOMENTUM: 0.9
  NESTEROV: False
  OPTIMIZER: adamw
  PATIENCE: 5
  RESUME: False
  SCHEDULER: ReduceLROnPlateau
  SHUFFLE: True
  WD: 0.0001
  factor: 0.5
WORKERS: 4
